import Foundation
import SwiftUI
import Combine

public enum HushTunnelLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case persian = "fa"
    case russian = "ru"
    case chinese = "zh"
    case turkish = "tr"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .english: return "English"
        case .persian: return "فارسی (Persian)"
        case .russian: return "Русский (Russian)"
        case .chinese: return "中文 (Chinese)"
        case .turkish: return "Türkçe (Turkish)"
        }
    }

    public var isRTL: Bool {
        return self == .persian
    }
}

@MainActor
public final class LanguageManager: ObservableObject {
    public static let shared = LanguageManager()

    @Published public var currentLanguage: HushTunnelLanguage = .english {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: "app_language")
        }
    }

    public var layoutDirection: LayoutDirection {
        currentLanguage.isRTL ? .rightToLeft : .leftToRight
    }

    private init() {
        let saved = UserDefaults.standard.string(forKey: "app_language") ?? "en"
        self.currentLanguage = HushTunnelLanguage(rawValue: saved) ?? .english
    }

    public func setLanguage(_ lang: HushTunnelLanguage) {
        self.currentLanguage = lang
    }

    public func tr(_ key: String) -> String {
        return HushTunnelStrings.get(key, lang: currentLanguage)
    }
}

public struct HushTunnelStrings {
    private static let translations: [HushTunnelLanguage: [String: String]] = [
        .english: [
            "web.storeNotice": "Account & Subscription Management",
            "web.storeDesc": "Subscriptions, active devices, and partner licenses are managed via your web dashboard:",
            "web.storeUrl": "https://www.hushtunnel.com",
            "web.paymentMethods": "Manage your active services, devices, and security settings online.",
            "web.resellerNotice": "Accounts registered through authorized partners can be managed directly or with your provider.",
            "reseller.topupNotice": "Balance & Billing Management",
            "reseller.topupDesc": "Reseller balance deposits and billing invoices are managed through your online web portal.",
            "reseller.topupBtn": "Manage Balance at hushtunnel.com",
            "account.changePassword": "Change Password",
            "account.currentPassword": "Current Password",
            "account.newPassword": "New Password",
            "account.passwordSuccess": "Password updated successfully",
            "account.title": "Account Settings",
            "auth.login": "Log in",
            "auth.register": "Sign up",
            "auth.email": "Email address",
            "auth.password": "Password",
            "auth.signIn": "Sign In",
            "auth.signUp": "Create Account",
            "auth.dontHaveAccount": "Don't have an account?",
            "auth.alreadyHaveAccount": "Already have an account?",
            "vpn.connect": "Connect",
            "vpn.disconnect": "Disconnect",
            "vpn.connecting": "Connecting...",
            "vpn.preparing": "Preparing...",
            "vpn.connected": "Connected",
            "vpn.disconnected": "Disconnected",
            "vpn.activePlan": "Active Plan",
            "vpn.expires": "Expires",
            "vpn.daysRemaining": "%d days left",
            "vpn.trafficUsed": "Usage",
            "vpn.buyPlan": "Get a Subscription",
            "vpn.renew": "Renew Subscription",
            "vpn.noSub": "No active VPN connection",
            "vpn.noSubDesc": "Select a plan below to activate your high-speed VLESS connection.",
            "vpn.qrCode": "QR Code",
            "orders.title": "Order History",
            "reseller.portal": "Reseller Portal",
            "reseller.balance": "Prepaid Balance",
            "reseller.discount": "Current Discount",
            "reseller.nextTier": "Add $%@ for %d%% off",
            "reseller.tab.vpn": "My VPN",
            "reseller.tab.overview": "Dashboard",
            "reseller.tab.customers": "Customers",
            "reseller.tab.subscriptions": "Subscriptions",
            "reseller.tab.orders": "Orders",
            "reseller.tab.deposits": "Transactions",
            "reseller.tab.transactions": "Transactions",
            "reseller.tab.subresellers": "Sub-Resellers",
            "reseller.createMyVpn": "Create My Personal VPN",
            "reseller.addCustomer": "Add Customer",
            "reseller.newOrder": "New Order for Customer",
            "reseller.addFunds": "Deposit Funds",
            "reseller.resetPassword": "Reset Password",
            "reseller.changePassword": "Set Custom Password",
            "reseller.extend": "Extend Days",
            "reseller.revoke": "Revoke",
            "reseller.addSubReseller": "Add Sub-Reseller",
            "reseller.subresellers.empty": "No sub-resellers yet.",
            "reseller.subresellers.stats": "%d customers · %d subscriptions",
            "reseller.subresellers.initialBalance": "Initial Balance (USD)",
            "reseller.transferFunds": "Transfer Funds",
            "reseller.transfer.availableBalance": "Available Balance: $%@",
            "reseller.transfer.remainingBalance": "Remaining After: $%@",
            "reseller.transfer.recipientEmail": "Recipient Email",
            "reseller.transfer.amountUsd": "Amount ($ USD)",
            "reseller.transfer.note": "Note / Description (Optional)",
            "reseller.transfer.confirm": "Confirm Transfer",
            "reseller.transfer.success": "Transfer completed successfully",
            "reseller.subresellers.details": "Sub-Reseller Details",
            "reseller.subresellers.addFunds": "Add Funds",
            "reseller.insufficientBalance": "Insufficient wallet balance",
            "reseller.serverDefault": "Default",
            "common.cancel": "Cancel",
            "common.confirm": "Confirm",
            "common.done": "Done",
            "common.language": "Language",
            "common.logout": "Log out",
            "common.refresh": "Refresh",
            "common.close": "Close",
            "common.copy": "Copy",
            "common.copied": "Copied to clipboard"
        ],
        .persian: [
            "web.storeNotice": "مدیریت حساب و اشتراک",
            "web.storeDesc": "مدیریت اشتراک‌ها، اتصال دستگاه‌ها و تنظیمات حساب از طریق پورتال وب انجام می‌شود:",
            "web.storeUrl": "https://www.hushtunnel.com",
            "web.paymentMethods": "تنظیمات اشتراک و مدیریت سرویس‌ها از طریق پنل کاربری آنلاین در دسترس است.",
            "web.resellerNotice": "حساب‌های دریافت شده از نمایندگان مجاز نیز از طریق نماینده یا پنل کاربری قابل مدیریت است.",
            "reseller.topupNotice": "مدیریت اعتبار و حساب نمایندگی",
            "reseller.topupDesc": "مدیریت حساب و افزایش اعتبار نمایندگی از طریق پرتال رسمی وب انجام می‌شود.",
            "reseller.topupBtn": "مدیریت حساب در hushtunnel.com",
            "account.changePassword": "تغییر رمز عبور",
            "account.currentPassword": "رمز عبور فعلی",
            "account.newPassword": "رمز عبور جدید",
            "account.passwordSuccess": "رمز عبور با موفقیت تغییر یافت",
            "account.title": "تنظیمات حساب",
            "auth.login": "ورود به حساب",
            "auth.register": "ثبت نام",
            "auth.email": "آدرس ایمیل",
            "auth.password": "کلمه عبور",
            "auth.signIn": "ورود",
            "auth.signUp": "ایجاد حساب کاربری",
            "auth.dontHaveAccount": "حساب کاربری ندارید؟",
            "auth.alreadyHaveAccount": "قبلاً ثبت نام کرده‌اید؟",
            "vpn.connect": "اتصال سریع",
            "vpn.disconnect": "قطع اتصال",
            "vpn.connecting": "در حال اتصال...",
            "vpn.preparing": "در حال آماده‌سازی...",
            "vpn.connected": "متصل شد",
            "vpn.disconnected": "قطع شد",
            "vpn.activePlan": "اشتراک فعال",
            "vpn.expires": "تاریخ انقضا",
            "vpn.daysRemaining": "%d روز باقی مانده",
            "vpn.trafficUsed": "مصرف ترافیک",
            "vpn.buyPlan": "خرید اشتراک جدید",
            "vpn.renew": "تمدید اشتراک",
            "vpn.noSub": "اشتراک فعالی ندارید",
            "vpn.noSubDesc": "برای فعال‌سازی کانکشن ضد فیلتر پرسرعت، یک پلن انتخاب کنید.",
            "vpn.qrCode": "کد QR",
            "orders.title": "تاریخچه سفارشات",
            "reseller.portal": "پنل همکاران و نمایندگان",
            "reseller.balance": "موجودی کیف پول",
            "reseller.discount": "تخفیف فعلی شما",
            "reseller.nextTier": "شارژ $%@ برای %d%% تخفیف",
            "reseller.tab.vpn": "اتصال من",
            "reseller.tab.overview": "داشبورد",
            "reseller.tab.customers": "مشتریان",
            "reseller.tab.subscriptions": "اشتراک‌ها",
            "reseller.tab.orders": "سفارشات",
            "reseller.tab.deposits": "افزایش موجودی",
            "reseller.tab.subresellers": "نمایندگان زیرمجموعه",
            "reseller.tab.transactions": "تراکنش‌ها",
            "reseller.createMyVpn": "ایجاد اتصال اختصاصی برای خودم",
            "reseller.addCustomer": "افزودن کاربر جدید",
            "reseller.newOrder": "ثبت اشتراک برای کاربر",
            "reseller.addFunds": "افزایش موجودی کیف پول",
            "reseller.resetPassword": "بازنشانی کلمه عبور",
            "reseller.changePassword": "تعیین پسورد دلخواه",
            "reseller.extend": "تمدید روزها",
            "reseller.revoke": "حذف و ابطال",
            "reseller.addSubReseller": "افزودن نماینده زیرمجموعه",
            "reseller.subresellers.empty": "هنوز نماینده زیرمجموعه‌ای ندارید.",
            "reseller.subresellers.stats": "%d مشتری · %d اشتراک",
            "reseller.subresellers.initialBalance": "موجودی اولیه (دلار)",
            "reseller.transferFunds": "انتقال موجودی",
            "reseller.transfer.availableBalance": "موجودی در دسترس: %@ دلار",
            "reseller.transfer.remainingBalance": "باقیمانده پس از انتقال: %@ دلار",
            "reseller.transfer.recipientEmail": "ایمیل گیرنده",
            "reseller.transfer.amountUsd": "مبلغ (دلار)",
            "reseller.transfer.note": "یادداشت / توضیحات (اختیاری)",
            "reseller.transfer.confirm": "تایید و انتقال",
            "reseller.transfer.success": "انتقال با موفقیت انجام شد",
            "reseller.subresellers.details": "مشخصات نماینده همکار",
            "reseller.subresellers.addFunds": "افزایش موجودی",
            "reseller.insufficientBalance": "موجودی کیف پول کافی نیست",
            "reseller.serverDefault": "پیش‌فرض",
            "common.cancel": "انصراف",
            "common.confirm": "تایید",
            "common.done": "تمام",
            "common.language": "تغییر زبان",
            "common.logout": "خروج از حساب",
            "common.refresh": "بروزرسانی",
            "common.close": "بستن",
            "common.copy": "کپی",
            "common.copied": "کپی شد"
        ],
        .russian: [
            "web.storeNotice": "Управление аккаунтом и подпиской",
            "web.storeDesc": "Управление подписками, устройствами и параметрами доступно на веб-портале:",
            "web.storeUrl": "https://www.hushtunnel.com",
            "web.paymentMethods": "Управляйте активными сервисами и настройками безопасности в личном кабинете.",
            "web.resellerNotice": "Аккаунты, оформленные через партнеров, можно продлевать у вашего провайдера или онлайн.",
            "reseller.topupNotice": "Управление балансом реселлера",
            "reseller.topupDesc": "Пополнение баланса и управление счетами реселлера осуществляются на веб-портале.",
            "reseller.topupBtn": "Управление балансом на hushtunnel.com",
            "account.changePassword": "Сменить пароль",
            "account.currentPassword": "Текущий пароль",
            "account.newPassword": "Новый пароль",
            "account.passwordSuccess": "Пароль успешно обновлен",
            "account.title": "Настройки аккаунта",
            "auth.login": "Вход",
            "auth.register": "Регистрация",
            "auth.email": "Электронная почта",
            "auth.password": "Пароль",
            "auth.signIn": "Войти",
            "auth.signUp": "Создать аккаунт",
            "auth.dontHaveAccount": "Нет аккаунта?",
            "auth.alreadyHaveAccount": "Уже есть аккаунт?",
            "vpn.connect": "Подключиться",
            "vpn.disconnect": "Отключиться",
            "vpn.connecting": "Подключение...",
            "vpn.preparing": "Подготовка...",
            "vpn.connected": "Подключено",
            "vpn.disconnected": "Отключено",
            "vpn.activePlan": "Активный тариф",
            "vpn.expires": "Истекает",
            "vpn.daysRemaining": "Осталось %d дн.",
            "vpn.trafficUsed": "Трафик",
            "vpn.buyPlan": "Купить тариф",
            "vpn.renew": "Продлить тариф",
            "vpn.noSub": "Нет активной подписки",
            "vpn.noSubDesc": "Выберите тариф ниже для подключения к VPN.",
            "vpn.qrCode": "QR-код",
            "orders.title": "История заказов",
            "reseller.portal": "Кабинет реселлера",
            "reseller.balance": "Баланс кошелька",
            "reseller.discount": "Скидка реселлера",
            "reseller.nextTier": "+$%@ для скидки %d%%",
            "reseller.tab.vpn": "Мой VPN",
            "reseller.tab.overview": "Обзор",
            "reseller.tab.customers": "Клиенты",
            "reseller.tab.subscriptions": "Подписки",
            "reseller.tab.orders": "Заказы",
            "reseller.tab.deposits": "Транзакции",
            "reseller.tab.transactions": "Транзакции",
            "reseller.tab.subresellers": "Субреселлеры",
            "reseller.createMyVpn": "Создать личный VPN",
            "reseller.addCustomer": "Добавить клиента",
            "reseller.newOrder": "Оформить для клиента",
            "reseller.addFunds": "Пополнить баланс",
            "reseller.resetPassword": "Сбросить пароль",
            "reseller.changePassword": "Задать новый пароль",
            "reseller.extend": "Продлить дни",
            "reseller.revoke": "Отозвать",
            "reseller.addSubReseller": "Добавить субреселлера",
            "reseller.subresellers.empty": "Пока нет субреселлеров.",
            "reseller.subresellers.stats": "%d клиентов · %d подписок",
            "reseller.subresellers.initialBalance": "Начальный баланс (USD)",
            "reseller.transferFunds": "Перевести средства",
            "reseller.transfer.availableBalance": "Доступный баланс: $%@",
            "reseller.transfer.remainingBalance": "Остаток после: $%@",
            "reseller.transfer.recipientEmail": "Email получателя",
            "reseller.transfer.amountUsd": "Сумма ($ USD)",
            "reseller.transfer.note": "Примечание (необязательно)",
            "reseller.transfer.confirm": "Подтвердить перевод",
            "reseller.transfer.success": "Перевод успешно выполнен",
            "reseller.subresellers.details": "Данные суб-реселлера",
            "reseller.subresellers.addFunds": "Пополнить баланс",
            "reseller.insufficientBalance": "Недостаточно средств на балансе",
            "reseller.serverDefault": "По умолчанию",
            "common.cancel": "Отмена",
            "common.confirm": "Подтвердить",
            "common.done": "Готово",
            "common.language": "Язык",
            "common.logout": "Выйти",
            "common.refresh": "Обновить",
            "common.close": "Закрыть",
            "common.copy": "Копировать",
            "common.copied": "Скопировано"
        ],
        .chinese: [
            "web.storeNotice": "账户与订阅管理",
            "web.storeDesc": "如需管理订阅、设备接入及账户配置，请访问官方网页控制台：",
            "web.storeUrl": "https://www.hushtunnel.com",
            "web.paymentMethods": "在在线个人中心管理您的生效服务及安全设置。",
            "web.resellerNotice": "通过分销合作伙伴开通的账户，可通过服务商或官方网站进行统一管理。",
            "reseller.topupNotice": "分销商账户与余额管理",
            "reseller.topupDesc": "分销商余额充值与账单管理请前往官方网页控制台进行。",
            "reseller.topupBtn": "在 hushtunnel.com 管理账户",
            "account.changePassword": "修改密码",
            "account.currentPassword": "当前密码",
            "account.newPassword": "新密码",
            "account.passwordSuccess": "密码修改成功",
            "account.title": "账户设置",
            "auth.login": "登录",
            "auth.register": "注册",
            "auth.email": "电子邮箱",
            "auth.password": "密码",
            "auth.signIn": "登录",
            "auth.signUp": "创建账户",
            "auth.dontHaveAccount": "还没有账户？",
            "auth.alreadyHaveAccount": "已有账户？",
            "vpn.connect": "一键连接",
            "vpn.disconnect": "断开连接",
            "vpn.connecting": "正在连接...",
            "vpn.preparing": "正在准备...",
            "vpn.connected": "已连接",
            "vpn.disconnected": "未连接",
            "vpn.activePlan": "当前订阅",
            "vpn.expires": "到期时间",
            "vpn.daysRemaining": "剩余 %d 天",
            "vpn.trafficUsed": "已用流量",
            "vpn.buyPlan": "购买套餐",
            "vpn.renew": "续费订阅",
            "vpn.noSub": "暂无有效订阅",
            "vpn.noSubDesc": "请在下方选择套餐以开启高速 VLESS 节点。",
            "vpn.qrCode": "二维码",
            "orders.title": "订单记录",
            "reseller.portal": "代理商后台",
            "reseller.balance": "账户余额",
            "reseller.discount": "当前折扣",
            "reseller.nextTier": "充值 $%@ 可享 %d%% 折扣",
            "reseller.tab.vpn": "我的VPN",
            "reseller.tab.overview": "总览",
            "reseller.tab.customers": "客户列表",
            "reseller.tab.subscriptions": "订阅管理",
            "reseller.tab.orders": "订单管理",
            "reseller.tab.deposits": "交易记录",
            "reseller.tab.transactions": "交易记录",
            "reseller.tab.subresellers": "下级代理",
            "reseller.createMyVpn": "开通个人专属VPN",
            "reseller.addCustomer": "添加新客户",
            "reseller.newOrder": "为客户开通套餐",
            "reseller.addFunds": "充值余额",
            "reseller.resetPassword": "重置密码",
            "reseller.changePassword": "修改自定义密码",
            "reseller.extend": "增加天数",
            "reseller.revoke": "删除注销",
            "reseller.addSubReseller": "添加下级代理",
            "reseller.subresellers.empty": "暂无下级代理。",
            "reseller.subresellers.stats": "%d 位客户 · %d 个订阅",
            "reseller.subresellers.initialBalance": "初始余额（美元）",
            "reseller.insufficientBalance": "钱包余额不足",
            "reseller.serverDefault": "默认",
            "common.cancel": "取消",
            "common.confirm": "确认",
            "common.done": "完成",
            "common.language": "语言",
            "common.logout": "退出登录",
            "common.refresh": "刷新",
            "common.close": "关闭",
            "common.copy": "复制",
            "common.copied": "已复制"
        ],
        .turkish: [
            "web.storeNotice": "Hesap ve Abonelik Yönetimi",
            "web.storeDesc": "Aboneliklerinizi, cihazlarınızı ve hesap ayarlarınızı web portalımızdan yönetebilirsiniz:",
            "web.storeUrl": "https://www.hushtunnel.com",
            "web.paymentMethods": "Hizmetlerinizi ve güvenlik ayarlarınızı çevrimiçi kontrol panelinden yönetin.",
            "web.resellerNotice": "Yetkili iş ortaklarımız üzerinden açılan hesaplar bayinizden veya web portalından yönetilebilir.",
            "reseller.topupNotice": "Bayi Bakiye Yönetimi",
            "reseller.topupDesc": "Bayi bakiye yüklemeleri ve fatura işlemleri web portalımız üzerinden yönetilir.",
            "reseller.topupBtn": "hushtunnel.com üzerinden yönetin",
            "account.changePassword": "Şifre Değiştir",
            "account.currentPassword": "Mevcut Şifre",
            "account.newPassword": "Yeni Şifre",
            "account.passwordSuccess": "Şifre başarıyla güncellendi",
            "account.title": "Hesap Ayarları",
            "auth.login": "Giriş Yap",
            "auth.register": "Kayıt Ol",
            "auth.email": "E-posta Adresi",
            "auth.password": "Şifre",
            "auth.signIn": "Giriş Yap",
            "auth.signUp": "Hesap Oluştur",
            "auth.dontHaveAccount": "Hesabınız yok mu?",
            "auth.alreadyHaveAccount": "Zaten hesabınız var mı?",
            "vpn.connect": "Bağlan",
            "vpn.disconnect": "Bağlantıyı Kes",
            "vpn.connecting": "Bağlanıyor...",
            "vpn.preparing": "Hazırlanıyor...",
            "vpn.connected": "Bağlandı",
            "vpn.disconnected": "Bağlantı Yok",
            "vpn.activePlan": "Aktif Plan",
            "vpn.expires": "Bitiş Tarihi",
            "vpn.daysRemaining": "%d gün kaldı",
            "vpn.trafficUsed": "Kullanım",
            "vpn.buyPlan": "Plan Satın Al",
            "vpn.renew": "Planı Yenile",
            "vpn.noSub": "Aktif bağlantı bulunamadı",
            "vpn.noSubDesc": "VLESS bağlantınızı etkinleştirmek için bir plan seçin.",
            "vpn.qrCode": "QR Kodu",
            "orders.title": "Sipariş Geçmişi",
            "reseller.portal": "Bayi Portalı",
            "reseller.balance": "Bakiye",
            "reseller.discount": "Mevcut İndirim",
            "reseller.nextTier": "%%d indirim için $%@ ekleyin",
            "reseller.tab.vpn": "VPN Bağlantım",
            "reseller.tab.overview": "Panel",
            "reseller.tab.customers": "Müşteriler",
            "reseller.tab.subscriptions": "Abonelikler",
            "reseller.tab.orders": "Siparişler",
            "reseller.tab.deposits": "Yüklemeler",
            "reseller.tab.subresellers": "Alt Bayiler",
            "reseller.createMyVpn": "Kişisel VPN Oluştur",
            "reseller.addCustomer": "Müşteri Ekle",
            "reseller.newOrder": "Müşteriye Plan Tanımla",
            "reseller.addFunds": "Bakiye Yükle",
            "reseller.resetPassword": "Şifreyi Sıfırla",
            "reseller.changePassword": "Yeni Şifre Belirle",
            "reseller.extend": "Süre Uzat",
            "reseller.revoke": "İptal Et",
            "reseller.addSubReseller": "Alt Bayi Ekle",
            "reseller.subresellers.empty": "Henüz alt bayi yok.",
            "reseller.subresellers.stats": "%d müşteri · %d abonelik",
            "reseller.subresellers.initialBalance": "Başlangıç Bakiyesi (USD)",
            "reseller.transferFunds": "Bakiye Transferi",
            "reseller.transfer.availableBalance": "Kullanılabilir Bakiye: $%@",
            "reseller.transfer.remainingBalance": "Kalan Bakiye: $%@",
            "reseller.transfer.recipientEmail": "Alıcı E-posta",
            "reseller.transfer.amountUsd": "Tutar ($ USD)",
            "reseller.transfer.note": "Not / Açıklama (İsteğe bağlı)",
            "reseller.transfer.confirm": "Transferi Onayla",
            "reseller.transfer.success": "Transfer başarıyla tamamlandı",
            "reseller.subresellers.details": "Alt Bayi Detayları",
            "reseller.subresellers.addFunds": "Bakiye Ekle",
            "reseller.insufficientBalance": "Yetersiz bakiye",
            "reseller.serverDefault": "Varsayılan",
            "common.cancel": "İptal",
            "common.confirm": "Onayla",
            "common.done": "Tamam",
            "common.language": "Dil",
            "common.logout": "Çıkış Yap",
            "common.refresh": "Yenile",
            "common.close": "Kapat",
            "common.copy": "Kopyala",
            "common.copied": "Kopyalandı"
        ]
    ]

    public static func get(_ key: String, lang: HushTunnelLanguage) -> String {
        return translations[lang]?[key] ?? translations[.english]?[key] ?? key
    }
}
