import Foundation
import SwiftUI
import Combine

public enum HushTunnelLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case persian = "fa"
    case russian = "ru"
    case chinese = "zh"
    case turkish = "tr"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .english: return "English"
        case .persian: return "فارسی (Persian)"
        case .russian: return "Русский (Russian)"
        case .chinese: return "中文 (Chinese)"
        case .turkish: return "Türkçe (Turkish)"
        }
    }

    public var isRTL: Bool {
        return self == .persian
    }
}

@MainActor
public final class LanguageManager: ObservableObject {
    public static let shared = LanguageManager()

    @Published public var currentLanguage: HushTunnelLanguage = .english {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: "app_language")
        }
    }

    public var layoutDirection: LayoutDirection {
        currentLanguage.isRTL ? .rightToLeft : .leftToRight
    }

    private init() {
        let saved = UserDefaults.standard.string(forKey: "app_language") ?? "en"
        self.currentLanguage = HushTunnelLanguage(rawValue: saved) ?? .english
    }

    public func setLanguage(_ lang: HushTunnelLanguage) {
        self.currentLanguage = lang
    }

    public func tr(_ key: String) -> String {
        return HushTunnelStrings.get(key, lang: currentLanguage)
    }
}

public struct HushTunnelStrings {
    private static let translations: [HushTunnelLanguage: [String: String]] = [
        .english: [
            "web.storeNotice": "Account & Subscription Management",
            "web.storeDesc": "Manage subscriptions, devices, and account security in HushTunnel.",
            "web.storeUrl": "Account settings",
            "web.paymentMethods": "App Store purchases are available in the app.",
            "web.resellerNotice": "Partner-provided accounts can also be managed with your provider.",
            "reseller.topupNotice": "Balance & Billing Management",
            "reseller.topupDesc": "Add reseller balance securely with an in-app purchase.",
            "reseller.topupBtn": "Add Funds",
            "account.changePassword": "Change Password",
            "account.currentPassword": "Current Password",
            "account.newPassword": "New Password",
            "account.passwordSuccess": "Password updated successfully",
            "account.title": "Account Settings",
            "auth.login": "Log in",
            "auth.register": "Sign up",
            "auth.email": "Email address",
            "auth.password": "Password",
            "auth.signIn": "Sign In",
            "auth.signUp": "Create Account",
            "auth.dontHaveAccount": "Don't have an account?",
            "auth.alreadyHaveAccount": "Already have an account?",
            "vpn.connect": "Connect",
            "vpn.disconnect": "Disconnect",
            "vpn.connecting": "Connecting...",
            "vpn.preparing": "Preparing...",
            "vpn.testConnection": "Test Connection",
            "vpn.testing": "Testing...",
            "vpn.testSuccess": "Connected: %dms · IP: %@",
            "vpn.testIpMismatch": "Unprotected: IP is %@",
            "vpn.testFailed": "Connection Failed",
            "vpn.connected": "Connected",
            "vpn.disconnected": "Disconnected",
            "vpn.activePlan": "Active Plan",
            "vpn.expires": "Expires",
            "vpn.daysRemaining": "%d days left",
            "vpn.trafficUsed": "Usage",
            "vpn.buyPlan": "Get a Subscription",
            "vpn.renew": "Renew Subscription",
            "vpn.noSub": "No active VPN connection",
            "vpn.noServer": "No server is available",
            "vpn.noSubDesc": "Select a plan below to activate your high-speed VLESS connection.",
            "vpn.qrCode": "QR Code",
            "orders.title": "Order History",
            "reseller.portal": "Reseller Portal",
            "reseller.balance": "Prepaid Balance",
            "reseller.discount": "Current Discount",
            "reseller.nextTier": "Add $%@ for %d%% off",
            "reseller.tab.vpn": "My VPN",
            "reseller.tab.overview": "Dashboard",
            "reseller.tab.customers": "Customers",
            "reseller.tab.subscriptions": "Subscriptions",
            "reseller.tab.orders": "Orders",
            "reseller.tab.deposits": "Transactions",
            "reseller.tab.transactions": "Transactions",
            "reseller.tab.subresellers": "Sub-Resellers",
            "reseller.createMyVpn": "Create My Personal VPN",
            "reseller.addCustomer": "Add Customer",
            "reseller.newOrder": "New Order for Customer",
            "reseller.addFunds": "Deposit Funds",
            "reseller.resetPassword": "Reset Password",
            "reseller.changePassword": "Set Custom Password",
            "reseller.extend": "Extend Days",
            "reseller.revoke": "Revoke",
            "reseller.showAdvancedLinks": "Show per-server links (advanced)",
            "reseller.hideAdvancedLinks": "Hide per-server links",
            "reseller.advancedLinksHint": "These are single-server links without DNS settings. For apps like V2Box, NekoBox, or Shadowrocket, use the Subscription link above instead — it includes DNS settings, lists all servers, and updates automatically.",
            "reseller.subStatusActive": "Active",
            "reseller.subStatusDisabled": "Disabled",
            "reseller.toggleDisable": "Disable",
            "reseller.toggleEnable": "Enable",
            "reseller.resetUuid": "Reset UUID",
            "reseller.searchSubscriptions": "Search subscriptions...",
            "reseller.manageSubscriptionSection": "Manage Subscription",
            "reseller.extendDescription": "Adds 30 more days to this customer's plan using their current setup. Use this when a customer has paid to keep using the service.",
            "reseller.disableDescription": "Immediately stops this customer from connecting, without deleting anything. Use this to pause access — for example if a payment is late — you can turn it back on anytime.",
            "reseller.enableDescription": "Turns this customer's access back on so they can connect again with their existing settings.",
            "reseller.resetUuidDescription": "Creates a brand-new secret connection code for this customer. Their old QR code and link will stop working right away, and they will need the new one to connect again. Only do this if their old link may have been shared with someone else.",
            "reseller.revokeDescription": "Permanently deletes this customer's subscription and disconnects them for good. This cannot be undone. If you only want to pause them, use Disable instead.",
            "reseller.confirmDisableSubTitle": "Disable subscription?",
            "reseller.confirmDisableSubMessage": "%@ will lose VPN access immediately. You can re-enable it anytime.",
            "reseller.confirmResetUuidTitle": "Reset connection ID?",
            "reseller.confirmResetUuidMessage": "%@'s current VLESS link and QR code will stop working immediately. Share the new one with them after this.",
            "reseller.confirmRevokeTitle": "Revoke subscription?",
            "reseller.confirmRevokeMessage": "This permanently deletes %@'s subscription from the server. This can't be undone.",
            "reseller.addSubReseller": "Add Sub-Reseller",
            "reseller.subresellers.empty": "No sub-resellers yet.",
            "reseller.subresellers.stats": "%d customers · %d subscriptions",
            "reseller.subresellers.initialBalance": "Initial Balance (USD)",
            "reseller.transferFunds": "Transfer Funds",
            "reseller.transfer.availableBalance": "Available Balance: $%@",
            "reseller.transfer.remainingBalance": "Remaining After: $%@",
            "reseller.transfer.recipientEmail": "Recipient Email",
            "reseller.transfer.amountUsd": "Amount ($ USD)",
            "reseller.transfer.note": "Note / Description (Optional)",
            "reseller.transfer.confirm": "Confirm Transfer",
            "reseller.transfer.success": "Transfer completed successfully",
            "reseller.subresellers.details": "Sub-Reseller Details",
            "reseller.subresellers.addFunds": "Add Funds",
            "reseller.insufficientBalance": "Insufficient wallet balance",
            "reseller.serverDefault": "Default",
            "reseller.searchExistingCustomer": "Search existing customers",
            "reseller.noMatchingCustomers": "No matching customers",
            "common.cancel": "Cancel",
            "common.confirm": "Confirm",
            "common.done": "Done",
            "common.language": "Language",
            "common.logout": "Log out",
            "common.refresh": "Refresh",
            "common.close": "Close",
            "common.copy": "Copy",
            "common.copied": "Copied to clipboard",
            "debug.logsTitle": "Connection Logs",
            "tx.transferOut": "Transfer to %@",
            "tx.transferIn": "Transfer from %@",
            "tx.deposit": "Wallet deposit (%@)",
            "tx.planPurchase": "Plan purchase: %@",
            "tx.orderPayment": "Order payment (%@)",
            "tx.personalSubscription": "Personal VPN subscription: %@",
            "tx.personalRenewal": "Personal VPN renewal: %@",
            "tx.createdAccountOrder": "Created account & order: %@ (%@)",
            "tx.orderForCustomer": "Order for %@ (%@)",
            "tx.subResellerInitialBalance": "Initial balance for sub-reseller %@",
            "tx.startupBalanceFromParent": "Initial startup balance from parent reseller",
            "iap.title": "Subscriptions & Funds", "iap.description": "Purchases are securely processed by the App Store. Subscription purchases renew automatically until canceled in your Apple account.",
            "iap.subscriptions": "Auto-renewing subscriptions", "iap.addFunds": "Add wallet funds", "iap.restore": "Restore purchases",
            "iap.storeBillingNote": "HushTunnel never receives or stores your card details. Wallet funds do not expire.", "iap.unavailable": "In-app purchases are not available yet.",
            "iap.subscriptionDays": "%d days of access", "iap.walletCredit": "$%.0f wallet credit", "iap.purchaseProcessing": "Purchase confirmed. Your account is being updated…", "iap.restoreComplete": "Purchases restored.",
            "privacy.title": "Privacy", "privacy.noActivityLogs": "No browsing or activity logs", "privacy.minimumData": "We keep only the minimum account, subscription, aggregate quota, and payment records required to operate the service. We do not retain browsing activity, traffic destinations, DNS queries, or VPN payloads.",
            "account.manageStoreSubscription": "Manage App Store subscription", "account.storeSubscriptionWarning": "Deleting your HushTunnel account does not cancel an Apple subscription. Cancel it here first to prevent future charges.",
            "account.deleteTitle": "Permanently Delete Account", "account.deleteDescription": "This immediately revokes every VPN credential and permanently removes your account, subscriptions, and identifying data. Your wallet balance and remaining service will be lost. Only anonymized accounting records are retained.",
            "account.deleteResellerWarning": "Your customers and sub-resellers will be reassigned to your parent reseller or the administrator level.", "account.typeDelete": "Type DELETE to confirm", "account.deleteButton": "Delete Account Permanently",
            "account.deleteConfirmTitle": "Delete this account?", "account.deleteConfirmMessage": "This is irreversible. Store subscriptions must be canceled separately.",
            "privacy.policy": "Privacy Policy", "terms.title": "Terms & Conditions", "auth.legalNotice": "By creating an account, you agree to the Terms & Conditions and acknowledge the Privacy Policy.",
            "vpnDisclosure.title": "HushTunnel needs VPN access",
            "vpnDisclosure.intro": "Please review this disclosure before using the VPN.",
            "vpnDisclosure.core": "HushTunnel uses Apple's Network Extension only to create the secure device-level VPN tunnel you request.",
            "vpnDisclosure.processing": "While connected, network packets, destination addresses, ports, DNS requests, and payloads pass transiently through your device and selected VPN endpoint so traffic can be routed. The tunnel from your device to that endpoint is encrypted.",
            "vpnDisclosure.data": "We do not retain browsing activity, traffic destinations, DNS requests, or VPN payloads. We keep account and subscription details, aggregate bytes used for quota, purchase records, and limited temporary security diagnostics.",
            "vpnDisclosure.monetization": "Except for transient processing required to provide the VPN you request, we do not sell, use, or disclose VPN traffic data to third parties for any purpose, and never redirect or manipulate it for advertising or monetization.",
            "vpnDisclosure.choice": "Tap Agree to enable VPN features. Tap Not now to decline and sign out. You can withdraw consent later by signing out and deleting your account.",
            "vpnDisclosure.accept": "Agree and Continue", "vpnDisclosure.decline": "Not now"
        ],
        .persian: [
            "web.storeNotice": "مدیریت حساب و اشتراک",
            "web.storeDesc": "اشتراک‌ها، دستگاه‌ها و امنیت حساب را در HushTunnel مدیریت کنید.",
            "web.storeUrl": "تنظیمات حساب",
            "web.paymentMethods": "خرید App Store در برنامه در دسترس است.",
            "web.resellerNotice": "حساب‌های نمایندگی را می‌توان با ارائه‌دهنده نیز مدیریت کرد.",
            "reseller.topupNotice": "مدیریت اعتبار و حساب نمایندگی",
            "reseller.topupDesc": "اعتبار نمایندگی را با خرید درون‌برنامه‌ای افزایش دهید.",
            "reseller.topupBtn": "افزایش موجودی",
            "account.changePassword": "تغییر رمز عبور",
            "account.currentPassword": "رمز عبور فعلی",
            "account.newPassword": "رمز عبور جدید",
            "account.passwordSuccess": "رمز عبور با موفقیت تغییر یافت",
            "account.title": "تنظیمات حساب",
            "auth.login": "ورود به حساب",
            "auth.register": "ثبت نام",
            "auth.email": "آدرس ایمیل",
            "auth.password": "کلمه عبور",
            "auth.signIn": "ورود",
            "auth.signUp": "ایجاد حساب کاربری",
            "auth.dontHaveAccount": "حساب کاربری ندارید؟",
            "auth.alreadyHaveAccount": "قبلاً ثبت نام کرده‌اید؟",
            "vpn.connect": "اتصال سریع",
            "vpn.disconnect": "قطع اتصال",
            "vpn.connecting": "در حال اتصال...",
            "vpn.preparing": "در حال آماده‌سازی...",
            "vpn.testConnection": "تست اتصال",
            "vpn.testing": "در حال بررسی...",
            "vpn.testSuccess": "اتصال تایید شد: %d میلی‌ثانیه · آی‌پی: %@",
            "vpn.testIpMismatch": "غیر امن: آی‌پی شما %@",
            "vpn.testFailed": "خطا در برقراری ارتباط",
            "vpn.connected": "متصل شد",
            "vpn.disconnected": "قطع شد",
            "vpn.activePlan": "اشتراک فعال",
            "vpn.expires": "تاریخ انقضا",
            "vpn.daysRemaining": "%d روز باقی مانده",
            "vpn.trafficUsed": "مصرف ترافیک",
            "vpn.buyPlan": "خرید اشتراک جدید",
            "vpn.renew": "تمدید اشتراک",
            "vpn.noSub": "اشتراک فعالی ندارید",
            "vpn.noServer": "هیچ سروری در دسترس نیست",
            "vpn.noSubDesc": "برای فعال‌سازی کانکشن ضد فیلتر پرسرعت، یک پلن انتخاب کنید.",
            "vpn.qrCode": "کد QR",
            "orders.title": "تاریخچه سفارشات",
            "reseller.portal": "پنل همکاران و نمایندگان",
            "reseller.balance": "موجودی کیف پول",
            "reseller.discount": "تخفیف فعلی شما",
            "reseller.nextTier": "شارژ $%@ برای %d%% تخفیف",
            "reseller.tab.vpn": "اتصال من",
            "reseller.tab.overview": "داشبورد",
            "reseller.tab.customers": "مشتریان",
            "reseller.tab.subscriptions": "اشتراک‌ها",
            "reseller.tab.orders": "سفارشات",
            "reseller.tab.deposits": "افزایش موجودی",
            "reseller.tab.subresellers": "نمایندگان زیرمجموعه",
            "reseller.tab.transactions": "تراکنش‌ها",
            "reseller.createMyVpn": "ایجاد اتصال اختصاصی برای خودم",
            "reseller.addCustomer": "افزودن کاربر جدید",
            "reseller.newOrder": "ثبت اشتراک برای کاربر",
            "reseller.addFunds": "افزایش موجودی کیف پول",
            "reseller.resetPassword": "بازنشانی کلمه عبور",
            "reseller.changePassword": "تعیین پسورد دلخواه",
            "reseller.extend": "تمدید روزها",
            "reseller.revoke": "حذف و ابطال",
            "reseller.showAdvancedLinks": "نمایش لینک‌های هر سرور (پیشرفته)",
            "reseller.hideAdvancedLinks": "پنهان کردن لینک‌های هر سرور",
            "reseller.advancedLinksHint": "این لینک‌ها فقط برای یک سرور هستند و تنظیمات DNS ندارند. اگر از اپلیکیشن‌هایی مثل V2Box، NekoBox یا Shadowrocket استفاده می‌کنید، به‌جای این‌ها از لینک اشتراک بالا استفاده کنید؛ چون شامل تنظیمات DNS است، همه سرورها را نشان می‌دهد و به‌صورت خودکار به‌روزرسانی می‌شود.",
            "reseller.subStatusActive": "فعال",
            "reseller.subStatusDisabled": "غیرفعال",
            "reseller.toggleDisable": "غیرفعال کردن",
            "reseller.toggleEnable": "فعال کردن",
            "reseller.resetUuid": "بازنشانی شناسه",
            "reseller.searchSubscriptions": "جستجوی اشتراک‌ها...",
            "reseller.manageSubscriptionSection": "مدیریت اشتراک",
            "reseller.extendDescription": "۳۰ روز دیگر به اشتراک این مشتری با همان تنظیمات فعلی اضافه می‌شود. از این گزینه زمانی استفاده کنید که مشتری برای ادامه استفاده از سرویس پرداخت کرده است.",
            "reseller.disableDescription": "دسترسی این مشتری برای اتصال بلافاصله قطع می‌شود، بدون اینکه چیزی حذف شود. از این گزینه برای توقف موقت دسترسی استفاده کنید — مثلاً وقتی پرداخت مشتری با تأخیر مواجه شده — و هر زمان می‌توانید دوباره آن را فعال کنید.",
            "reseller.enableDescription": "دسترسی این مشتری دوباره فعال می‌شود تا بتواند با تنظیمات قبلی خود متصل شود.",
            "reseller.resetUuidDescription": "یک کد اتصال محرمانه کاملاً جدید برای این مشتری ساخته می‌شود. کد QR و لینک قبلی او بلافاصله از کار می‌افتد و برای اتصال دوباره باید کد جدید را دریافت کند. این کار را فقط زمانی انجام دهید که احتمال می‌دهید لینک قبلی او در اختیار شخص دیگری قرار گرفته باشد.",
            "reseller.revokeDescription": "اشتراک این مشتری برای همیشه حذف می‌شود و دسترسی او به طور کامل قطع خواهد شد. این کار قابل بازگشت نیست. اگر فقط می‌خواهید دسترسی را موقتاً متوقف کنید، از گزینه «غیرفعال کردن» استفاده کنید.",
            "reseller.confirmDisableSubTitle": "اشتراک غیرفعال شود؟",
            "reseller.confirmDisableSubMessage": "%@ بلافاصله دسترسی VPN را از دست می‌دهد. هر زمان می‌توانید دوباره فعالش کنید.",
            "reseller.confirmResetUuidTitle": "شناسه اتصال بازنشانی شود؟",
            "reseller.confirmResetUuidMessage": "لینک VLESS و کد QR فعلی %@ بلافاصله از کار می‌افتد. لینک جدید را بعد از این با او به اشتراک بگذارید.",
            "reseller.confirmRevokeTitle": "اشتراک ابطال شود؟",
            "reseller.confirmRevokeMessage": "این کار اشتراک %@ را برای همیشه از سرور حذف می‌کند. غیرقابل بازگشت است.",
            "reseller.addSubReseller": "افزودن نماینده زیرمجموعه",
            "reseller.subresellers.empty": "هنوز نماینده زیرمجموعه‌ای ندارید.",
            "reseller.subresellers.stats": "%d مشتری · %d اشتراک",
            "reseller.subresellers.initialBalance": "موجودی اولیه (دلار)",
            "reseller.transferFunds": "انتقال موجودی",
            "reseller.transfer.availableBalance": "موجودی در دسترس: %@ دلار",
            "reseller.transfer.remainingBalance": "باقیمانده پس از انتقال: %@ دلار",
            "reseller.transfer.recipientEmail": "ایمیل گیرنده",
            "reseller.transfer.amountUsd": "مبلغ (دلار)",
            "reseller.transfer.note": "یادداشت / توضیحات (اختیاری)",
            "reseller.transfer.confirm": "تایید و انتقال",
            "reseller.transfer.success": "انتقال با موفقیت انجام شد",
            "reseller.subresellers.details": "مشخصات نماینده همکار",
            "reseller.subresellers.addFunds": "افزایش موجودی",
            "reseller.insufficientBalance": "موجودی کیف پول کافی نیست",
            "reseller.serverDefault": "پیش‌فرض",
            "reseller.searchExistingCustomer": "جستجوی مشتریان موجود",
            "reseller.noMatchingCustomers": "مشتری مطابقی پیدا نشد",
            "common.cancel": "انصراف",
            "common.confirm": "تایید",
            "common.done": "تمام",
            "common.language": "تغییر زبان",
            "common.logout": "خروج از حساب",
            "common.refresh": "بروزرسانی",
            "common.close": "بستن",
            "common.copy": "کپی",
            "common.copied": "کپی شد",
            "debug.logsTitle": "گزارش‌های اتصال",
            "tx.transferOut": "انتقال به %@",
            "tx.transferIn": "انتقال از %@",
            "tx.deposit": "واریز به کیف پول (%@)",
            "tx.planPurchase": "خرید پلن: %@",
            "tx.orderPayment": "پرداخت سفارش (%@)",
            "tx.personalSubscription": "اشتراک شخصی VPN: %@",
            "tx.personalRenewal": "تمدید اشتراک شخصی VPN: %@",
            "tx.createdAccountOrder": "ایجاد حساب و سفارش: %@ (%@)",
            "tx.orderForCustomer": "سفارش برای %@ (%@)",
            "tx.subResellerInitialBalance": "موجودی اولیه برای نماینده زیرمجموعه %@",
            "tx.startupBalanceFromParent": "موجودی اولیه راه‌اندازی از نماینده والد",
            "iap.title": "اشتراک و افزایش موجودی", "iap.description": "خریدها به‌صورت امن توسط App Store انجام می‌شوند. اشتراک تا زمان لغو در حساب Apple به‌طور خودکار تمدید می‌شود.",
            "iap.subscriptions": "اشتراک‌های با تمدید خودکار", "iap.addFunds": "افزایش موجودی کیف پول", "iap.restore": "بازیابی خریدها",
            "iap.storeBillingNote": "HushTunnel اطلاعات کارت شما را دریافت یا ذخیره نمی‌کند. اعتبار کیف پول منقضی نمی‌شود.", "iap.unavailable": "خرید درون‌برنامه‌ای هنوز در دسترس نیست.",
            "iap.subscriptionDays": "%d روز دسترسی", "iap.walletCredit": "$%.0f اعتبار کیف پول", "iap.purchaseProcessing": "خرید تأیید شد. حساب شما در حال به‌روزرسانی است…", "iap.restoreComplete": "خریدها بازیابی شدند.",
            "privacy.title": "حریم خصوصی", "privacy.noActivityLogs": "بدون ثبت مرور یا فعالیت", "privacy.minimumData": "فقط حداقل اطلاعات حساب، اشتراک، مجموع مصرف و پرداخت لازم برای ارائه سرویس را نگه می‌داریم. فعالیت مرور، مقصد ترافیک، درخواست DNS یا محتوای VPN ذخیره نمی‌شود.",
            "account.manageStoreSubscription": "مدیریت اشتراک App Store", "account.storeSubscriptionWarning": "حذف حساب HushTunnel اشتراک Apple را لغو نمی‌کند. برای جلوگیری از پرداخت بعدی ابتدا آن را اینجا لغو کنید.",
            "account.deleteTitle": "حذف دائمی حساب", "account.deleteDescription": "این کار فوراً همه دسترسی‌های VPN را لغو و حساب، اشتراک‌ها و اطلاعات هویتی را برای همیشه حذف می‌کند. موجودی و سرویس باقی‌مانده از بین می‌رود. فقط سوابق مالی ناشناس نگهداری می‌شود.",
            "account.deleteResellerWarning": "مشتریان و زیرنمایندگان به نماینده بالادست یا سطح مدیر منتقل می‌شوند.", "account.typeDelete": "برای تأیید DELETE را وارد کنید", "account.deleteButton": "حذف دائمی حساب",
            "account.deleteConfirmTitle": "این حساب حذف شود؟", "account.deleteConfirmMessage": "این کار برگشت‌ناپذیر است. اشتراک فروشگاه باید جداگانه لغو شود.",
            "privacy.policy": "سیاست حفظ حریم خصوصی", "terms.title": "شرایط و ضوابط", "auth.legalNotice": "با ایجاد حساب، با شرایط و ضوابط موافقت می‌کنید و سیاست حفظ حریم خصوصی را می‌پذیرید.",
            "vpnDisclosure.title": "HushTunnel به دسترسی VPN نیاز دارد",
            "vpnDisclosure.intro": "لطفاً پیش از استفاده از VPN این توضیحات را بررسی کنید.",
            "vpnDisclosure.core": "HushTunnel فقط برای ایجاد تونل امن VPN در سطح دستگاه که شما درخواست می‌کنید، از Network Extension اپل استفاده می‌کند.",
            "vpnDisclosure.processing": "هنگام اتصال، بسته‌های شبکه، نشانی مقصد، پورت‌ها، درخواست‌های DNS و محتوای ترافیک فقط به‌طور گذرا در دستگاه و نقطه پایانی VPN انتخابی پردازش می‌شوند تا ترافیک هدایت شود. تونل بین دستگاه و آن نقطه پایانی رمزگذاری شده است.",
            "vpnDisclosure.data": "فعالیت مرور، مقصدهای ترافیک، درخواست‌های DNS یا محتوای VPN را نگهداری نمی‌کنیم. اطلاعات حساب و اشتراک، مجموع بایت مصرفی برای سهمیه، سوابق خرید و اطلاعات تشخیصی امنیتی محدود و موقت نگهداری می‌شوند.",
            "vpnDisclosure.monetization": "به‌جز پردازش گذرای لازم برای ارائه VPN درخواستی، داده ترافیک VPN را برای هیچ هدفی نمی‌فروشیم، استفاده نمی‌کنیم یا در اختیار شخص ثالث قرار نمی‌دهیم و آن را برای تبلیغ یا کسب درآمد تغییر مسیر نمی‌دهیم.",
            "vpnDisclosure.choice": "برای فعال شدن امکانات VPN «موافقم و ادامه» را بزنید. با انتخاب «فعلاً نه» درخواست را رد کرده و خارج می‌شوید. بعداً نیز می‌توانید با خروج و حذف حساب، رضایت خود را پس بگیرید.",
            "vpnDisclosure.accept": "موافقم و ادامه", "vpnDisclosure.decline": "فعلاً نه"
        ],
        .russian: [
            "web.storeNotice": "Управление аккаунтом и подпиской",
            "web.storeDesc": "Управляйте подписками, устройствами и безопасностью аккаунта в HushTunnel.",
            "web.storeUrl": "Настройки аккаунта",
            "web.paymentMethods": "Покупки App Store доступны в приложении.",
            "web.resellerNotice": "Партнёрскими аккаунтами также можно управлять через провайдера.",
            "reseller.topupNotice": "Управление балансом реселлера",
            "reseller.topupDesc": "Пополняйте баланс реселлера покупкой в приложении.",
            "reseller.topupBtn": "Пополнить баланс",
            "account.changePassword": "Сменить пароль",
            "account.currentPassword": "Текущий пароль",
            "account.newPassword": "Новый пароль",
            "account.passwordSuccess": "Пароль успешно обновлен",
            "account.title": "Настройки аккаунта",
            "auth.login": "Вход",
            "auth.register": "Регистрация",
            "auth.email": "Электронная почта",
            "auth.password": "Пароль",
            "auth.signIn": "Войти",
            "auth.signUp": "Создать аккаунт",
            "auth.dontHaveAccount": "Нет аккаунта?",
            "auth.alreadyHaveAccount": "Уже есть аккаунт?",
            "vpn.connect": "Подключиться",
            "vpn.disconnect": "Отключиться",
            "vpn.connecting": "Подключение...",
            "vpn.preparing": "Подготовка...",
            "vpn.testConnection": "Проверить соединение",
            "vpn.testing": "Тестирование...",
            "vpn.testSuccess": "Подключено: %d мс · IP: %@",
            "vpn.testIpMismatch": "Не защищено: IP %@",
            "vpn.testFailed": "Ошибка соединения",
            "vpn.connected": "Подключено",
            "vpn.disconnected": "Отключено",
            "vpn.activePlan": "Активный тариф",
            "vpn.expires": "Истекает",
            "vpn.daysRemaining": "Осталось %d дн.",
            "vpn.trafficUsed": "Трафик",
            "vpn.buyPlan": "Купить тариф",
            "vpn.renew": "Продлить тариф",
            "vpn.noSub": "Нет активной подписки",
            "vpn.noServer": "Нет доступных серверов",
            "vpn.noSubDesc": "Выберите тариф ниже для подключения к VPN.",
            "vpn.qrCode": "QR-код",
            "orders.title": "История заказов",
            "reseller.portal": "Кабинет реселлера",
            "reseller.balance": "Баланс кошелька",
            "reseller.discount": "Скидка реселлера",
            "reseller.nextTier": "+$%@ для скидки %d%%",
            "reseller.tab.vpn": "Мой VPN",
            "reseller.tab.overview": "Обзор",
            "reseller.tab.customers": "Клиенты",
            "reseller.tab.subscriptions": "Подписки",
            "reseller.tab.orders": "Заказы",
            "reseller.tab.deposits": "Транзакции",
            "reseller.tab.transactions": "Транзакции",
            "reseller.tab.subresellers": "Субреселлеры",
            "reseller.createMyVpn": "Создать личный VPN",
            "reseller.addCustomer": "Добавить клиента",
            "reseller.newOrder": "Оформить для клиента",
            "reseller.addFunds": "Пополнить баланс",
            "reseller.resetPassword": "Сбросить пароль",
            "reseller.changePassword": "Задать новый пароль",
            "reseller.extend": "Продлить дни",
            "reseller.revoke": "Отозвать",
            "reseller.showAdvancedLinks": "Показать ссылки по серверам (доп.)",
            "reseller.hideAdvancedLinks": "Скрыть ссылки по серверам",
            "reseller.advancedLinksHint": "Это ссылки на один сервер без настроек DNS. Если вы используете V2Box, NekoBox, Shadowrocket или похожее приложение, используйте ссылку подписки выше — она включает настройки DNS, показывает все серверы и обновляется автоматически.",
            "reseller.subStatusActive": "Активна",
            "reseller.subStatusDisabled": "Отключена",
            "reseller.toggleDisable": "Отключить",
            "reseller.toggleEnable": "Включить",
            "reseller.resetUuid": "Сбросить UUID",
            "reseller.searchSubscriptions": "Поиск подписок...",
            "reseller.manageSubscriptionSection": "Управление подпиской",
            "reseller.extendDescription": "Добавляет клиенту ещё 30 дней с текущими настройками. Используйте это, если клиент оплатил продолжение обслуживания.",
            "reseller.disableDescription": "Немедленно блокирует подключение клиента, ничего не удаляя. Используйте это, чтобы временно приостановить доступ — например, при задержке оплаты — и включить его снова в любой момент.",
            "reseller.enableDescription": "Снова включает доступ клиента, чтобы он мог подключаться с прежними настройками.",
            "reseller.resetUuidDescription": "Создаёт для клиента совершенно новый секретный код подключения. Старый QR-код и ссылка сразу перестанут работать, и клиенту потребуется новая ссылка. Делайте это только если старая ссылка могла попасть к посторонним.",
            "reseller.revokeDescription": "Полностью и безвозвратно удаляет подписку клиента и отключает его. Отменить это действие нельзя. Если нужно лишь временно приостановить доступ, используйте «Отключить».",
            "reseller.confirmDisableSubTitle": "Отключить подписку?",
            "reseller.confirmDisableSubMessage": "%@ немедленно потеряет доступ к VPN. Вы можете снова включить её в любое время.",
            "reseller.confirmResetUuidTitle": "Сбросить ID подключения?",
            "reseller.confirmResetUuidMessage": "Текущая ссылка VLESS и QR-код пользователя %@ немедленно перестанут работать. Отправьте ему новую ссылку после этого.",
            "reseller.confirmRevokeTitle": "Отозвать подписку?",
            "reseller.confirmRevokeMessage": "Это навсегда удалит подписку %@ с сервера. Это действие нельзя отменить.",
            "reseller.addSubReseller": "Добавить субреселлера",
            "reseller.subresellers.empty": "Пока нет субреселлеров.",
            "reseller.subresellers.stats": "%d клиентов · %d подписок",
            "reseller.subresellers.initialBalance": "Начальный баланс (USD)",
            "reseller.transferFunds": "Перевести средства",
            "reseller.transfer.availableBalance": "Доступный баланс: $%@",
            "reseller.transfer.remainingBalance": "Остаток после: $%@",
            "reseller.transfer.recipientEmail": "Email получателя",
            "reseller.transfer.amountUsd": "Сумма ($ USD)",
            "reseller.transfer.note": "Примечание (необязательно)",
            "reseller.transfer.confirm": "Подтвердить перевод",
            "reseller.transfer.success": "Перевод успешно выполнен",
            "reseller.subresellers.details": "Данные суб-реселлера",
            "reseller.subresellers.addFunds": "Пополнить баланс",
            "reseller.insufficientBalance": "Недостаточно средств на балансе",
            "reseller.serverDefault": "По умолчанию",
            "reseller.searchExistingCustomer": "Поиск существующих клиентов",
            "reseller.noMatchingCustomers": "Клиенты не найдены",
            "common.cancel": "Отмена",
            "common.confirm": "Подтвердить",
            "common.done": "Готово",
            "common.language": "Язык",
            "common.logout": "Выйти",
            "common.refresh": "Обновить",
            "common.close": "Закрыть",
            "common.copy": "Копировать",
            "common.copied": "Скопировано",
            "debug.logsTitle": "Журналы подключения",
            "tx.transferOut": "Перевод пользователю %@",
            "tx.transferIn": "Перевод от %@",
            "tx.deposit": "Пополнение кошелька (%@)",
            "tx.planPurchase": "Покупка тарифа: %@",
            "tx.orderPayment": "Оплата заказа (%@)",
            "tx.personalSubscription": "Личная подписка VPN: %@",
            "tx.personalRenewal": "Продление личной подписки VPN: %@",
            "tx.createdAccountOrder": "Создан аккаунт и заказ: %@ (%@)",
            "tx.orderForCustomer": "Заказ для %@ (%@)",
            "tx.subResellerInitialBalance": "Начальный баланс для субреселлера %@",
            "tx.startupBalanceFromParent": "Начальный баланс от родительского реселлера",
            "iap.title": "Подписки и баланс", "iap.description": "Покупки безопасно обрабатываются App Store. Подписка продлевается автоматически до отмены в аккаунте Apple.",
            "iap.subscriptions": "Автопродлеваемые подписки", "iap.addFunds": "Пополнить кошелёк", "iap.restore": "Восстановить покупки",
            "iap.storeBillingNote": "HushTunnel не получает и не хранит данные карты. Средства кошелька не сгорают.", "iap.unavailable": "Встроенные покупки пока недоступны.",
            "iap.subscriptionDays": "%d дней доступа", "iap.walletCredit": "$%.0f на кошелёк", "iap.purchaseProcessing": "Покупка подтверждена. Аккаунт обновляется…", "iap.restoreComplete": "Покупки восстановлены.",
            "privacy.title": "Конфиденциальность", "privacy.noActivityLogs": "Без журналов просмотра и активности", "privacy.minimumData": "Мы храним только минимальные данные аккаунта, подписки, общего трафика и платежей. История просмотра, назначения трафика, DNS-запросы и содержимое VPN не сохраняются.",
            "account.manageStoreSubscription": "Управление подпиской App Store", "account.storeSubscriptionWarning": "Удаление HushTunnel не отменяет подписку Apple. Сначала отмените её здесь, чтобы избежать новых списаний.",
            "account.deleteTitle": "Удалить аккаунт навсегда", "account.deleteDescription": "Все VPN-данные доступа будут немедленно отозваны, а аккаунт, подписки и идентифицирующие данные удалены навсегда. Баланс и остаток сервиса сгорят. Сохраняются только обезличенные финансовые записи.",
            "account.deleteResellerWarning": "Клиенты и субреселлеры будут переданы вышестоящему реселлеру либо администратору.", "account.typeDelete": "Введите DELETE для подтверждения", "account.deleteButton": "Удалить аккаунт навсегда",
            "account.deleteConfirmTitle": "Удалить этот аккаунт?", "account.deleteConfirmMessage": "Это необратимо. Подписку магазина нужно отменить отдельно.",
            "privacy.policy": "Политика конфиденциальности", "terms.title": "Условия использования", "auth.legalNotice": "Создавая аккаунт, вы соглашаетесь с Условиями использования и подтверждаете ознакомление с Политикой конфиденциальности.",
            "vpnDisclosure.title": "HushTunnel требуется доступ к VPN",
            "vpnDisclosure.intro": "Ознакомьтесь с этим уведомлением до использования VPN.",
            "vpnDisclosure.core": "HushTunnel использует Apple Network Extension только для создания запрошенного вами защищённого VPN-туннеля на уровне устройства.",
            "vpnDisclosure.processing": "Во время подключения сетевые пакеты, адреса назначения, порты, DNS-запросы и содержимое временно проходят через устройство и выбранный VPN-сервер для маршрутизации. Туннель от устройства до этого сервера зашифрован.",
            "vpnDisclosure.data": "Мы не сохраняем историю просмотра, назначения трафика, DNS-запросы или содержимое VPN. Хранятся данные аккаунта и подписки, суммарный объём для квоты, записи покупок и ограниченная временная диагностика безопасности.",
            "vpnDisclosure.monetization": "Кроме временной обработки для запрошенного VPN, мы ни для каких целей не продаём, не используем и не раскрываем третьим лицам данные VPN-трафика и не перенаправляем их ради рекламы или монетизации.",
            "vpnDisclosure.choice": "Нажмите «Согласиться и продолжить», чтобы включить VPN. «Не сейчас» означает отказ и выход. Позже согласие можно отозвать, выйдя и удалив аккаунт.",
            "vpnDisclosure.accept": "Согласиться и продолжить", "vpnDisclosure.decline": "Не сейчас"
        ],
        .chinese: [
            "web.storeNotice": "账户与订阅管理",
            "web.storeDesc": "在 HushTunnel 中管理订阅、设备和账户安全。",
            "web.storeUrl": "账户设置",
            "web.paymentMethods": "应用内可使用 App Store 购买。",
            "web.resellerNotice": "合作伙伴提供的账户也可由服务商管理。",
            "reseller.topupNotice": "分销商账户与余额管理",
            "reseller.topupDesc": "通过应用内购买安全充值分销商余额。",
            "reseller.topupBtn": "充值",
            "account.changePassword": "修改密码",
            "account.currentPassword": "当前密码",
            "account.newPassword": "新密码",
            "account.passwordSuccess": "密码修改成功",
            "account.title": "账户设置",
            "auth.login": "登录",
            "auth.register": "注册",
            "auth.email": "电子邮箱",
            "auth.password": "密码",
            "auth.signIn": "登录",
            "auth.signUp": "创建账户",
            "auth.dontHaveAccount": "还没有账户？",
            "auth.alreadyHaveAccount": "已有账户？",
            "vpn.connect": "一键连接",
            "vpn.disconnect": "断开连接",
            "vpn.connecting": "正在连接...",
            "vpn.preparing": "正在准备...",
            "vpn.testConnection": "测试连接",
            "vpn.testing": "正在测试...",
            "vpn.testSuccess": "连接已验证：%d毫秒 · IP: %@",
            "vpn.testIpMismatch": "未受保护：当前IP %@",
            "vpn.testFailed": "连接失败",
            "vpn.connected": "已连接",
            "vpn.disconnected": "未连接",
            "vpn.activePlan": "当前订阅",
            "vpn.expires": "到期时间",
            "vpn.daysRemaining": "剩余 %d 天",
            "vpn.trafficUsed": "已用流量",
            "vpn.buyPlan": "购买套餐",
            "vpn.renew": "续费订阅",
            "vpn.noSub": "暂无有效订阅",
            "vpn.noServer": "没有可用的服务器",
            "vpn.noSubDesc": "请在下方选择套餐以开启高速 VLESS 节点。",
            "vpn.qrCode": "二维码",
            "orders.title": "订单记录",
            "reseller.portal": "代理商后台",
            "reseller.balance": "账户余额",
            "reseller.discount": "当前折扣",
            "reseller.nextTier": "充值 $%@ 可享 %d%% 折扣",
            "reseller.tab.vpn": "我的VPN",
            "reseller.tab.overview": "总览",
            "reseller.tab.customers": "客户列表",
            "reseller.tab.subscriptions": "订阅管理",
            "reseller.tab.orders": "订单管理",
            "reseller.tab.deposits": "交易记录",
            "reseller.tab.transactions": "交易记录",
            "reseller.tab.subresellers": "下级代理",
            "reseller.createMyVpn": "开通个人专属VPN",
            "reseller.addCustomer": "添加新客户",
            "reseller.newOrder": "为客户开通套餐",
            "reseller.addFunds": "充值余额",
            "reseller.resetPassword": "重置密码",
            "reseller.changePassword": "修改自定义密码",
            "reseller.extend": "增加天数",
            "reseller.revoke": "删除注销",
            "reseller.showAdvancedLinks": "显示各服务器链接（高级）",
            "reseller.hideAdvancedLinks": "隐藏各服务器链接",
            "reseller.advancedLinksHint": "这些链接仅对应单个服务器，不包含 DNS 设置。如果你使用 V2Box、NekoBox、Shadowrocket 等应用，请改用上方的订阅链接——它包含 DNS 设置、显示所有服务器，并会自动更新。",
            "reseller.subStatusActive": "已启用",
            "reseller.subStatusDisabled": "已禁用",
            "reseller.toggleDisable": "禁用",
            "reseller.toggleEnable": "启用",
            "reseller.resetUuid": "重置 UUID",
            "reseller.searchSubscriptions": "搜索订阅...",
            "reseller.manageSubscriptionSection": "管理订阅",
            "reseller.extendDescription": "使用当前配置为该客户的套餐增加30天。当客户已付款需要继续使用服务时，请使用此操作。",
            "reseller.disableDescription": "立即阻止该客户连接，但不会删除任何数据。适用于需要临时暂停访问的情况，例如客户付款延迟——您可以随时重新启用。",
            "reseller.enableDescription": "重新启用该客户的访问权限，使其可以使用原有配置重新连接。",
            "reseller.resetUuidDescription": "为该客户生成一个全新的密钥连接码。客户原有的二维码和链接会立即失效，需要使用新链接才能重新连接。仅在怀疑原链接可能已泄露给他人时才使用此操作。",
            "reseller.revokeDescription": "永久删除该客户的订阅并彻底断开其连接，此操作无法撤销。如果只是想暂时暂停访问，请改用「禁用」。",
            "reseller.confirmDisableSubTitle": "禁用此订阅？",
            "reseller.confirmDisableSubMessage": "%@ 将立即失去 VPN 访问权限。您可以随时重新启用。",
            "reseller.confirmResetUuidTitle": "重置连接 ID？",
            "reseller.confirmResetUuidMessage": "%@ 当前的 VLESS 链接和二维码将立即失效。之后请将新链接分享给对方。",
            "reseller.confirmRevokeTitle": "注销此订阅？",
            "reseller.confirmRevokeMessage": "这将永久删除 %@ 在服务器上的订阅，且无法撤销。",
            "reseller.addSubReseller": "添加下级代理",
            "reseller.subresellers.empty": "暂无下级代理。",
            "reseller.subresellers.stats": "%d 位客户 · %d 个订阅",
            "reseller.subresellers.initialBalance": "初始余额（美元）",
            "reseller.insufficientBalance": "钱包余额不足",
            "reseller.serverDefault": "默认",
            "reseller.searchExistingCustomer": "搜索现有客户",
            "reseller.noMatchingCustomers": "未找到匹配的客户",
            "common.cancel": "取消",
            "common.confirm": "确认",
            "common.done": "完成",
            "common.language": "语言",
            "common.logout": "退出登录",
            "common.refresh": "刷新",
            "common.close": "关闭",
            "common.copy": "复制",
            "common.copied": "已复制",
            "debug.logsTitle": "连接日志",
            "tx.transferOut": "转账给 %@",
            "tx.transferIn": "来自 %@ 的转账",
            "tx.deposit": "钱包充值 (%@)",
            "tx.planPurchase": "购买套餐：%@",
            "tx.orderPayment": "订单付款 (%@)",
            "tx.personalSubscription": "个人 VPN 订阅：%@",
            "tx.personalRenewal": "个人 VPN 续费：%@",
            "tx.createdAccountOrder": "创建账户及订单：%@ (%@)",
            "tx.orderForCustomer": "为 %@ 下单 (%@)",
            "tx.subResellerInitialBalance": "下级代理 %@ 的初始余额",
            "tx.startupBalanceFromParent": "来自上级代理的初始启动余额",
            "iap.title": "订阅与充值", "iap.description": "购买由 App Store 安全处理。订阅会自动续订，直到您在 Apple 账户中取消。",
            "iap.subscriptions": "自动续订订阅", "iap.addFunds": "钱包充值", "iap.restore": "恢复购买",
            "iap.storeBillingNote": "HushTunnel 不会接收或保存银行卡信息。钱包余额不会过期。", "iap.unavailable": "应用内购买暂不可用。",
            "iap.subscriptionDays": "%d 天访问权限", "iap.walletCredit": "$%.0f 钱包余额", "iap.purchaseProcessing": "购买已确认，正在更新账户…", "iap.restoreComplete": "购买已恢复。",
            "privacy.title": "隐私", "privacy.noActivityLogs": "不记录浏览或活动日志", "privacy.minimumData": "我们只保留运营所需的最少账户、订阅、汇总配额和付款记录，不保留浏览活动、流量目的地、DNS 查询或 VPN 载荷。",
            "account.manageStoreSubscription": "管理 App Store 订阅", "account.storeSubscriptionWarning": "删除 HushTunnel 账户不会取消 Apple 订阅。请先在此取消，以免再次扣费。",
            "account.deleteTitle": "永久删除账户", "account.deleteDescription": "这会立即撤销所有 VPN 凭据，并永久删除账户、订阅和识别信息。钱包余额和剩余服务将丢失，仅保留匿名财务记录。",
            "account.deleteResellerWarning": "客户和下级经销商将转给上级经销商或管理员。", "account.typeDelete": "输入 DELETE 以确认", "account.deleteButton": "永久删除账户",
            "account.deleteConfirmTitle": "删除此账户？", "account.deleteConfirmMessage": "此操作不可撤销。商店订阅必须另行取消。",
            "privacy.policy": "隐私政策", "terms.title": "条款与条件", "auth.legalNotice": "创建账户即表示您同意《条款与条件》，并确认已阅读《隐私政策》。",
            "vpnDisclosure.title": "HushTunnel 需要 VPN 访问权限",
            "vpnDisclosure.intro": "请在使用 VPN 前阅读此披露说明。",
            "vpnDisclosure.core": "HushTunnel 仅使用 Apple Network Extension 创建您所请求的设备级安全 VPN 隧道。",
            "vpnDisclosure.processing": "连接期间，网络数据包、目标地址、端口、DNS 请求和载荷会暂时通过您的设备和所选 VPN 端点，以便路由流量。设备到该端点的隧道会被加密。",
            "vpnDisclosure.data": "我们不会保留浏览活动、流量目标、DNS 请求或 VPN 载荷。我们会保留账户和订阅信息、用于配额的汇总字节数、购买记录以及有限的临时安全诊断信息。",
            "vpnDisclosure.monetization": "除提供您所请求的 VPN 所必需的临时处理外，我们不会出于任何目的出售、使用或向第三方披露 VPN 流量数据，也不会为广告或获利而重定向或操纵流量。",
            "vpnDisclosure.choice": "点按“同意并继续”以启用 VPN 功能。点按“暂不”将拒绝并退出登录。您之后可通过退出并删除账户来撤回同意。",
            "vpnDisclosure.accept": "同意并继续", "vpnDisclosure.decline": "暂不"
        ],
        .turkish: [
            "web.storeNotice": "Hesap ve Abonelik Yönetimi",
            "web.storeDesc": "Abonelikleri, cihazları ve hesap güvenliğini HushTunnel içinde yönetin.",
            "web.storeUrl": "Hesap ayarları",
            "web.paymentMethods": "App Store satın alımları uygulamada kullanılabilir.",
            "web.resellerNotice": "İş ortağı hesapları sağlayıcınızla da yönetilebilir.",
            "reseller.topupNotice": "Bayi Bakiye Yönetimi",
            "reseller.topupDesc": "Uygulama içi satın alımla bayi bakiyenizi güvenle yükleyin.",
            "reseller.topupBtn": "Bakiye Ekle",
            "account.changePassword": "Şifre Değiştir",
            "account.currentPassword": "Mevcut Şifre",
            "account.newPassword": "Yeni Şifre",
            "account.passwordSuccess": "Şifre başarıyla güncellendi",
            "account.title": "Hesap Ayarları",
            "auth.login": "Giriş Yap",
            "auth.register": "Kayıt Ol",
            "auth.email": "E-posta Adresi",
            "auth.password": "Şifre",
            "auth.signIn": "Giriş Yap",
            "auth.signUp": "Hesap Oluştur",
            "auth.dontHaveAccount": "Hesabınız yok mu?",
            "auth.alreadyHaveAccount": "Zaten hesabınız var mı?",
            "vpn.connect": "Bağlan",
            "vpn.disconnect": "Bağlantıyı Kes",
            "vpn.connecting": "Bağlanıyor...",
            "vpn.preparing": "Hazırlanıyor...",
            "vpn.testConnection": "Bağlantıyı Test Et",
            "vpn.testing": "Test ediliyor...",
            "vpn.testSuccess": "Bağlantı Doğrulandı: %dms · IP: %@",
            "vpn.testIpMismatch": "Korumasız: IP %@",
            "vpn.testFailed": "Bağlantı Başarısız",
            "vpn.connected": "Bağlandı",
            "vpn.disconnected": "Bağlantı Yok",
            "vpn.activePlan": "Aktif Plan",
            "vpn.expires": "Bitiş Tarihi",
            "vpn.daysRemaining": "%d gün kaldı",
            "vpn.trafficUsed": "Kullanım",
            "vpn.buyPlan": "Plan Satın Al",
            "vpn.renew": "Planı Yenile",
            "vpn.noSub": "Aktif bağlantı bulunamadı",
            "vpn.noServer": "Kullanılabilir sunucu yok",
            "vpn.noSubDesc": "VLESS bağlantınızı etkinleştirmek için bir plan seçin.",
            "vpn.qrCode": "QR Kodu",
            "orders.title": "Sipariş Geçmişi",
            "reseller.portal": "Bayi Portalı",
            "reseller.balance": "Bakiye",
            "reseller.discount": "Mevcut İndirim",
            "reseller.nextTier": "%%d indirim için $%@ ekleyin",
            "reseller.tab.vpn": "VPN Bağlantım",
            "reseller.tab.overview": "Panel",
            "reseller.tab.customers": "Müşteriler",
            "reseller.tab.subscriptions": "Abonelikler",
            "reseller.tab.orders": "Siparişler",
            "reseller.tab.deposits": "Yüklemeler",
            "reseller.tab.subresellers": "Alt Bayiler",
            "reseller.createMyVpn": "Kişisel VPN Oluştur",
            "reseller.addCustomer": "Müşteri Ekle",
            "reseller.newOrder": "Müşteriye Plan Tanımla",
            "reseller.addFunds": "Bakiye Yükle",
            "reseller.resetPassword": "Şifreyi Sıfırla",
            "reseller.changePassword": "Yeni Şifre Belirle",
            "reseller.extend": "Süre Uzat",
            "reseller.revoke": "İptal Et",
            "reseller.showAdvancedLinks": "Sunucu bazlı bağlantıları göster (gelişmiş)",
            "reseller.hideAdvancedLinks": "Sunucu bazlı bağlantıları gizle",
            "reseller.advancedLinksHint": "Bunlar yalnızca tek bir sunucu için bağlantılardır ve DNS ayarları içermez. V2Box, NekoBox, Shadowrocket gibi uygulamalar kullanıyorsanız yukarıdaki Abonelik bağlantısını kullanın — DNS ayarlarını içerir, tüm sunucuları gösterir ve otomatik günceller.",
            "reseller.subStatusActive": "Aktif",
            "reseller.subStatusDisabled": "Devre Dışı",
            "reseller.toggleDisable": "Devre Dışı Bırak",
            "reseller.toggleEnable": "Etkinleştir",
            "reseller.resetUuid": "UUID Sıfırla",
            "reseller.searchSubscriptions": "Abonelik ara...",
            "reseller.manageSubscriptionSection": "Aboneliği Yönet",
            "reseller.extendDescription": "Bu müşterinin planına, mevcut ayarlarıyla 30 gün daha ekler. Müşteri hizmete devam etmek için ödeme yaptığında bunu kullanın.",
            "reseller.disableDescription": "Hiçbir şeyi silmeden müşterinin bağlanmasını hemen durdurur. Örneğin ödeme gecikmişse erişimi geçici olarak durdurmak için kullanın — istediğiniz zaman tekrar açabilirsiniz.",
            "reseller.enableDescription": "Müşterinin erişimini tekrar açar, böylece mevcut ayarlarıyla yeniden bağlanabilir.",
            "reseller.resetUuidDescription": "Bu müşteri için tamamen yeni bir gizli bağlantı kodu oluşturur. Eski QR kodu ve bağlantısı hemen çalışmayı durdurur, tekrar bağlanmak için yeni bağlantıya ihtiyaç duyar. Bunu yalnızca eski bağlantının başkasıyla paylaşılmış olabileceğini düşünüyorsanız yapın.",
            "reseller.revokeDescription": "Bu müşterinin aboneliğini kalıcı olarak siler ve bağlantısını tamamen keser. Bu işlem geri alınamaz. Sadece geçici olarak durdurmak istiyorsanız bunun yerine Devre Dışı Bırak seçeneğini kullanın.",
            "reseller.confirmDisableSubTitle": "Abonelik devre dışı bırakılsın mı?",
            "reseller.confirmDisableSubMessage": "%@ hemen VPN erişimini kaybedecek. İstediğiniz zaman tekrar etkinleştirebilirsiniz.",
            "reseller.confirmResetUuidTitle": "Bağlantı kimliği sıfırlansın mı?",
            "reseller.confirmResetUuidMessage": "%@ adlı müşterinin mevcut VLESS bağlantısı ve QR kodu hemen çalışmayı durduracak. Bundan sonra yeni bağlantıyı kendisiyle paylaşın.",
            "reseller.confirmRevokeTitle": "Abonelik iptal edilsin mi?",
            "reseller.confirmRevokeMessage": "Bu, %@ adlı müşterinin aboneliğini sunucudan kalıcı olarak siler. Bu işlem geri alınamaz.",
            "reseller.addSubReseller": "Alt Bayi Ekle",
            "reseller.subresellers.empty": "Henüz alt bayi yok.",
            "reseller.subresellers.stats": "%d müşteri · %d abonelik",
            "reseller.subresellers.initialBalance": "Başlangıç Bakiyesi (USD)",
            "reseller.transferFunds": "Bakiye Transferi",
            "reseller.transfer.availableBalance": "Kullanılabilir Bakiye: $%@",
            "reseller.transfer.remainingBalance": "Kalan Bakiye: $%@",
            "reseller.transfer.recipientEmail": "Alıcı E-posta",
            "reseller.transfer.amountUsd": "Tutar ($ USD)",
            "reseller.transfer.note": "Not / Açıklama (İsteğe bağlı)",
            "reseller.transfer.confirm": "Transferi Onayla",
            "reseller.transfer.success": "Transfer başarıyla tamamlandı",
            "reseller.subresellers.details": "Alt Bayi Detayları",
            "reseller.subresellers.addFunds": "Bakiye Ekle",
            "reseller.insufficientBalance": "Yetersiz bakiye",
            "reseller.serverDefault": "Varsayılan",
            "reseller.searchExistingCustomer": "Mevcut müşterilerde ara",
            "reseller.noMatchingCustomers": "Eşleşen müşteri bulunamadı",
            "common.cancel": "İptal",
            "common.confirm": "Onayla",
            "common.done": "Tamam",
            "common.language": "Dil",
            "common.logout": "Çıkış Yap",
            "common.refresh": "Yenile",
            "common.close": "Kapat",
            "common.copy": "Kopyala",
            "common.copied": "Kopyalandı",
            "debug.logsTitle": "Bağlantı Günlükleri",
            "tx.transferOut": "%@ kullanıcısına transfer",
            "tx.transferIn": "%@ kullanıcısından transfer",
            "tx.deposit": "Cüzdan yüklemesi (%@)",
            "tx.planPurchase": "Plan satın alma: %@",
            "tx.orderPayment": "Sipariş ödemesi (%@)",
            "tx.personalSubscription": "Kişisel VPN aboneliği: %@",
            "tx.personalRenewal": "Kişisel VPN yenileme: %@",
            "tx.createdAccountOrder": "Hesap ve sipariş oluşturuldu: %@ (%@)",
            "tx.orderForCustomer": "%@ için sipariş (%@)",
            "tx.subResellerInitialBalance": "%@ alt bayisi için başlangıç bakiyesi",
            "tx.startupBalanceFromParent": "Üst bayiden başlangıç bakiyesi",
            "iap.title": "Abonelikler ve Bakiye", "iap.description": "Satın alımlar App Store tarafından güvenle işlenir. Abonelik Apple hesabınızdan iptal edilene kadar otomatik yenilenir.",
            "iap.subscriptions": "Otomatik yenilenen abonelikler", "iap.addFunds": "Cüzdana bakiye ekle", "iap.restore": "Satın alımları geri yükle",
            "iap.storeBillingNote": "HushTunnel kart bilgilerinizi almaz veya saklamaz. Cüzdan bakiyesi sona ermez.", "iap.unavailable": "Uygulama içi satın alımlar henüz kullanılamıyor.",
            "iap.subscriptionDays": "%d günlük erişim", "iap.walletCredit": "$%.0f cüzdan bakiyesi", "iap.purchaseProcessing": "Satın alma onaylandı. Hesabınız güncelleniyor…", "iap.restoreComplete": "Satın alımlar geri yüklendi.",
            "privacy.title": "Gizlilik", "privacy.noActivityLogs": "Gezinme veya etkinlik günlüğü yok", "privacy.minimumData": "Yalnızca gerekli asgari hesap, abonelik, toplam kota ve ödeme kayıtlarını tutarız. Gezinme etkinliği, trafik hedefleri, DNS sorguları veya VPN içerikleri saklanmaz.",
            "account.manageStoreSubscription": "App Store aboneliğini yönet", "account.storeSubscriptionWarning": "HushTunnel hesabını silmek Apple aboneliğini iptal etmez. Yeni ücretleri önlemek için önce buradan iptal edin.",
            "account.deleteTitle": "Hesabı kalıcı olarak sil", "account.deleteDescription": "Tüm VPN kimlik bilgileri hemen iptal edilir; hesap, abonelikler ve kimlik verileri kalıcı olarak silinir. Bakiye ve kalan hizmet kaybedilir. Yalnızca anonim finans kayıtları tutulur.",
            "account.deleteResellerWarning": "Müşteriler ve alt bayiler üst bayiye veya yöneticiye aktarılır.", "account.typeDelete": "Onaylamak için DELETE yazın", "account.deleteButton": "Hesabı kalıcı olarak sil",
            "account.deleteConfirmTitle": "Bu hesap silinsin mi?", "account.deleteConfirmMessage": "Bu işlem geri alınamaz. Mağaza aboneliği ayrıca iptal edilmelidir.",
            "privacy.policy": "Gizlilik Politikası", "terms.title": "Şartlar ve Koşullar", "auth.legalNotice": "Hesap oluşturarak Şartlar ve Koşullar'ı kabul eder ve Gizlilik Politikası'nı okuduğunuzu onaylarsınız.",
            "vpnDisclosure.title": "HushTunnel VPN erişimine ihtiyaç duyar",
            "vpnDisclosure.intro": "VPN'i kullanmadan önce lütfen bu açıklamayı inceleyin.",
            "vpnDisclosure.core": "HushTunnel, yalnızca istediğiniz güvenli cihaz düzeyindeki VPN tünelini oluşturmak için Apple Network Extension kullanır.",
            "vpnDisclosure.processing": "Bağlıyken ağ paketleri, hedef adresler, bağlantı noktaları, DNS istekleri ve içerikler yönlendirme için cihazınızdan ve seçilen VPN uç noktasından geçici olarak geçer. Cihazınızdan bu uç noktaya kadar olan tünel şifrelidir.",
            "vpnDisclosure.data": "Gezinme etkinliğini, trafik hedeflerini, DNS isteklerini veya VPN içeriklerini saklamayız. Hesap ve abonelik bilgileri, kota için toplam kullanılan bayt, satın alma kayıtları ve sınırlı geçici güvenlik tanılamalarını saklarız.",
            "vpnDisclosure.monetization": "İstediğiniz VPN'i sağlamak için gereken geçici işleme dışında VPN trafik verisini hiçbir amaçla satmaz, kullanmaz veya üçüncü taraflara açıklamayız; reklam ya da para kazanma için yönlendirmeyiz.",
            "vpnDisclosure.choice": "VPN özelliklerini etkinleştirmek için Kabul Et ve Devam Et'e dokunun. Reddetmek ve çıkış yapmak için Şimdi değil'e dokunun. Daha sonra çıkış yapıp hesabınızı silerek onayınızı geri çekebilirsiniz.",
            "vpnDisclosure.accept": "Kabul Et ve Devam Et", "vpnDisclosure.decline": "Şimdi değil"
        ]
    ]

    public static func get(_ key: String, lang: HushTunnelLanguage) -> String {
        return translations[lang]?[key] ?? translations[.english]?[key] ?? key
    }
}
